-- Idempotent catalogue import generated from src/data/mockCatalog.ts
alter table public.products add column if not exists source_key text;
create unique index if not exists products_source_key_uidx on public.products(source_key);

with imported(source_key, vendor_name, name, description, category, price, image_url, is_available, ingredients, allergens, photo_status, image_quality_status, description_quality_status, is_bankable, is_public, status) as (
  values
  ('save-peyia-cote-porc', 'Snack Savè Peyi''A', 'Côte de porc riz crudités', 'Côte de porc grillée au feu de bois, tendre et savoureuse, servie avec du riz blanc parfumé et des crudités fraîches. Le plat signature de Snack Savè Peyi''A, un régal généreux fait maison ! 🔥', 'Plats', 12, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0005.jpg', true, 'Côte de porc grillée, riz blanc, salade verte, tomate, sauce maison.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-filet-poulet', 'Snack Savè Peyi''A', 'Filet de poulet', 'Filet de poulet grillé aux herbes, mariné maison, accompagné de riz parfumé, lentilles pays, légumes et crudités fraîches. Sain, généreux, fait maison avec amour ! 🐔', 'Plats', 10, null, true, 'Filet de poulet grillé, accompagné de riz, lentilles, légumes pays et crudités.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('save-peyia-crevettes', 'Snack Savè Peyi''A', 'Crevettes riz crudités', 'Crevettes sautées aux épices locales et oignons, servies avec du riz blanc et une salade fraîche croquante. Un plat léger et savoureux, parfait pour découvrir les saveurs de Snack Savè Peyi''A ! 🦐', 'Plats', 14, null, true, 'Crevettes sautées, oignons, tomates, riz blanc, salade verte, tomate, sauce maison.', 'Crustacés.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('save-peyia-cote-agneau', 'Snack Savè Peyi''A', 'Côte d''agneau', 'Côte d''agneau grillée aux épices, fondante et parfumée, servie avec frites maison, gratin, légumes pays ou riz au choix.', 'Plats', 16, null, true, 'Côte d''agneau grillée. Accompagnements : frites, gratin, légumes pays, riz, lentilles, bananes frites, crudités.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('save-peyia-entrecote', 'Snack Savè Peyi''A', 'Entrecôte', 'Entrecôte grillée, cuisson maîtrisée, servie avec frites maison croustillantes, gratin, légumes pays ou riz au choix. 🥩', 'Plats', 18, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0008.jpg', true, 'Entrecôte grillée. Accompagnements : frites, gratin, légumes pays, riz, lentilles, bananes frites, crudités.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-bavette', 'Snack Savè Peyi''A', 'Bavette de bœuf', 'Bavette de bœuf grillée, tendre et savoureuse, accompagnée de frites maison, gratin, légumes pays ou riz au choix.', 'Plats', 15, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0009.jpg', true, 'Bavette de bœuf grillée. Accompagnements : frites, gratin, légumes pays, riz, lentilles, bananes frites, crudités.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-cabri', 'Snack Savè Peyi''A', 'Cabri', 'Cabri grillé aux épices créoles, une spécialité antillaise généreuse, servie avec frites, gratin, légumes pays ou riz au choix. 🐐', 'Plats', 16, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0010.jpg', true, 'Cabri grillé. Accompagnements : frites, gratin, légumes pays, riz, lentilles, bananes frites, crudités.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-panini-saumon', 'Snack Savè Peyi''A', 'Panini saumon', 'Panini chaud garni de saumon, laitue, fromage râpé et sauce maison, toasté sur place. Idéal pour un déjeuner rapide et gourmand ! 🥪', 'Snacking', 8, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0011.jpg', true, 'Pain panini, saumon, laitue, fromage râpé, sauce maison.', 'Gluten, poisson, produits laitiers.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-cocktail-fruit', 'Snack Savè Peyi''A', 'Cocktail de fruits', 'Cocktail de fruits frais rafraîchissant — jus naturels, glaçons, citron vert, ananas. Sans alcool. Parfait pour se désaltérer sous le soleil martiniquais ! 🍍🥤', 'Snacking', 6, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0015.jpg', true, 'Jus de fruits frais, glaçons, citron vert, ananas.', 'Aucun.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-cocktail-alcool', 'Snack Savè Peyi''A', 'Cocktail fruits (alcool)', 'Cocktail de fruits frais avec alcool (rhum, punch). Rafraîchissant et festif, idéal pour les soirées vendredi et samedi au Pont de Fer ! 🍹', 'Snacking', 10, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0016.jpg', true, 'Jus de fruits frais, alcool (rhum/punch), glaçons, citron vert, ananas.', 'Alcool. Service réservé aux adultes.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-salade-fruits-assortie', 'Snack Savè Peyi''A', 'Salade de fruits frais', 'Salade de fruits frais de saison — ananas, pastèque, kiwi, raisins — en coupelle. Vitamines et fraîcheur garanties ! 🍉🍍', 'Snacking', 6, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0012.jpg', true, 'Fruits frais de saison (ananas, pastèque, kiwi, raisins).', 'Aucun.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('save-peyia-salade-fruits-rhum', 'Snack Savè Peyi''A', 'Salade de fruits au rhum', 'Salade de fruits frais de saison marinée au rhum arrangé. Une explosion de saveurs antillaises ! Idéal pour les soirées. 🥃', 'Snacking', 10, 'https://delikreol.com/vendors/save-peyia/drive-reimport/IMG-20260710-WA0013.jpg', true, 'Fruits frais de saison, rhum arrangé, glaçons.', 'Alcool. Service réservé aux adultes.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('antjecoco-pepite-gratin-banane', 'An Tjè Coco', 'Pépite façon gratin de banane jaune', 'Pépite artisanale salée façon gratin de banane jaune. Sur précommande du dimanche au mardi 12h, retrait mercredi ou jeudi/vendredi.', 'Plats', 9, null, true, 'Banane jaune, fromage râpé, œuf, épices antillaises, farine. Composition à valider avec la prestataire.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('antjecoco-pepite-coco-passion', 'An Tjè Coco', 'Pépite coco-passion', 'Pépite artisanale sucrée à la noix de coco et au fruit de la passion. Une douceur antillaise raffinée.', 'Desserts', 8, null, true, 'Noix de coco, fruit de la passion, farine, œufs. Composition à confirmer.', 'Gluten, œufs. Autres allergènes à confirmer.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('antjecoco-rougail-saucisses', 'An Tjè Coco', 'Pépite rougail saucisses', 'Pépite salée au rougail saucisses, une revisite créole de la crêpe gastronomique.', 'Plats', 10, null, true, 'Saucisses, tomate, oignons, épices. Composition à confirmer.', 'Gluten (blé). Sans œufs ni produits laitiers.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('antjecoco-tiramisu-cafe', 'An Tjè Coco', 'Pépite tiramisu café', 'Pépite sucrée façon tiramisu au café. Une fusion italo-créole en format bouchée.', 'Desserts', 8, null, true, 'Café, mascarpone, cacao. Composition à confirmer.', 'Gluten, produits laitiers. Autres allergènes à confirmer.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('cocos-food-paella-noire', 'Coco''s Food', 'Paella noire aux fruits de mer', 'Riz noir à l''encre de seiche, généreusement garni de crevettes, moules et morceaux de poisson, relevé de lanières de poivrons jaunes et rouges, petits pois et oignons frais. La spécialité signature de Coco''s Food, un plat marin riche en saveurs et en couleurs.', 'Plats', 15, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0081.jpg', true, 'Riz, encre de seiche, crevettes, moules, poisson blanc, poivrons, oignons, petits pois, épices.', 'Crustacés, mollusques, poisson.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-box-grille', 'Coco''s Food', 'Box grillé du marché', 'Viande de porc grillée marinée aux épices, cuite à la perfection avec une belle croûte caramélisée, servie avec un riz aux pois parfumé, du maïs doux, des carottes râpées et une salade de concombre frais. Un plat généreux relevé d''herbes fraîches.', 'Plats', 12, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0064.jpg', true, 'Viande de porc grillée, riz aux pois, maïs, carottes, concombre, oignons, herbes fraîches, épices.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-poulet-roti', 'Coco''s Food', 'Poulet rôti, riz & crudités', 'Pilons de poulet rôtis à la peau dorée et caramélisée, marinés aux herbes et épices, servis sur un lit de riz assaisonné. Accompagnés de chou rouge croquant, carottes râpées, maïs doux, salade verte et une salsa créole aux oignons et piment frais.', 'Plats', 11, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0066.jpg', true, 'Poulet, riz aux herbes, chou rouge, carottes, maïs, laitue, oignons, piment, épices.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-box-poisson-avocat', 'Coco''s Food', 'Box poisson & avocat', 'Chiquetaille de morue parfumée à l''huile et aux herbes, accompagnée de ti-nains (bananes vertes bouillies) fondants, d''une belle tranche d''avocat bien mûr, d''une salade de concombre et oignons croquants, le tout relevé d''une vinaigrette maison. Servi avec un jus de fruits cocktail artisanal.', 'Plats', 13, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0076.jpg', true, 'Morue effilochée, bananes vertes (ti-nain), avocat, concombre, oignons, herbes, huile, citron, piment.', 'Poisson.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-brochettes', 'Coco''s Food', 'Brochettes panées du marché', 'Pièces panées dorées et croustillantes, servies avec un accompagnement du jour. Plat généreux de marché, à confirmer selon disponibilité.', 'Plats', 12, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0077.jpg', true, 'Pièces panées, accompagnement du jour, herbes et épices. Composition exacte à confirmer avec la partenaire.', 'Gluten possible. Autres allergènes à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-friture', 'Coco''s Food', 'Friture caramélisée', 'Bananes plantains mûres frites caramélisées, mélangées à des morceaux de porc ou bœuf frits et des rondelles de saucisse, relevés d''oignons émincés et de piment. Un alloco-viande généreux aux saveurs sucrées-salées irrésistibles.', 'Snacking', 10, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0080.jpg', true, 'Banane plantain, viande de porc ou bœuf, saucisse, oignons, piment, huile, épices.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-plat-jour', 'Coco''s Food', 'Plat du jour complet', 'Bol généreux et équilibré : riz noir djon-djon aux petits pois, poisson ou viande effiloché(e) en sauce tomate épicée, dés de betteraves, salade verte croquante, oignons blancs, carottes râpées, maïs doux et rondelles de banane plantain. Un festival de saveurs et de couleurs qui change chaque jour.', 'Plats', 11, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0082.jpg', true, 'Riz djon-djon, poisson ou viande effiloché(e), betteraves, salade, oignons, carottes, maïs, banane plantain, épices.', 'Poisson. Autres à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-salade-viande', 'Coco''s Food', 'Salade de viande marinée', 'Salade fraîche et relevée : dés de viande ou pâté de porc marinés, mélangés à des oignons rouges croquants, de la cébette et du piment rouge frais, le tout assaisonné d''une sauce vinaigrée aux épices et au citron. Parfaite en entrée ou repas léger.', 'Snacking', 8, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0085.jpg', true, 'Viande marinée ou pâté de porc, oignons rouges, cébette, piment, citron, vinaigre, épices.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('cocos-food-spaghetti', 'Coco''s Food', 'Spaghetti sauté', 'Spaghettis sautés aux légumes — poivrons verts et rouges, oignons — et aux saucisses cocktail, relevés d''épices. Un plat de pâtes savoureux et généreux, parfait pour les petits et grands appétits.', 'Plats', 8, 'https://delikreol.com/vendors/coco/drive-reimport/IMG-20260526-WA0071.jpg', true, 'Spaghetti, saucisse cocktail, poivrons, oignons, épices, huile.', 'Gluten. Autres à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-attieke', 'Saveurs d''Afrique', 'Attiéké', 'Poisson grillé doré à la perfection, servi sur un lit d''attiéké (semoule de manioc fermentée), accompagné de banane plantain frite (alloco), crudités croquantes (chou, carotte, concombre) et mayonnaise maison. Deux sauces maison complètent le tableau : piment rouge relevé et oignons fondants confits. Un plat complet et parfumé, signature incontournable de la cuisine ivoirienne de rue.', 'Plats', 14, null, true, 'Poisson grillé, attiéké (manioc), banane plantain, chou, carotte, concombre, mayonnaise maison, piment rouge, oignon confit, épices.', 'Poisson, œuf (mayonnaise).', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('saveurs-afrique-foutou', 'Saveurs d''Afrique', 'Foutou banane sauce arachide', 'Foutou — banane plantain pilée à la perfection en une boule dense et élastique, servie avec une sauce arachide onctueuse et parfumée aux épices africaines. Accompagné de viande de mouton ou dinde longuement mijotée. Un grand classique ivoirien riche et réconfortant, où la douceur du plantain rencontre la rondeur de l''arachide.', 'Plats', 15, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0156.jpg', true, 'Banane plantain pilée, pâte d''arachide, viande de mouton ou dinde, tomate, oignon, piment, épices africaines.', 'Arachide.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-ablo', 'Saveurs d''Afrique', 'Ablo (Gâteau de riz)', 'Galettes de riz fermenté cuites à la vapeur, d''un blanc immaculé à la texture spongieuse et légèrement acidulée. Servies avec un poisson entier frit (tilapia) à la peau croustillante et dorée, accompagné d''une sauce tomate-piment rouge intense longuement réduite aux oignons et épices. L''ablo traditionnel ivoirien, doux et aérien, idéal pour absorber les saveurs puissantes de la sauce.', 'Plats', 15, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0155.jpg', true, 'Riz fermenté, maïs, poisson (tilapia), tomate, oignon, piment, huile de palme, épices.', 'Poisson.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-atassi', 'Saveurs d''Afrique', 'Atassi (riz aux haricots)', 'Atassi maison : riz aux haricots, généreux et nourrissant, servi avec sauce et accompagnement du jour selon disponibilité. Un classique simple, complet et réconfortant.', 'Plats', 12, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0158.jpg', true, 'Riz, haricots, sauce maison, épices. Accompagnement du jour à confirmer.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-sauce-legume', 'Saveurs d''Afrique', 'Sauce légume', 'Sauce légume africaine, riche et parfumée, préparée avec feuilles/légumes mijotés et épices. Servie avec l’accompagnement disponible du jour.', 'Plats', 13, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260612-WA0142.jpg', true, 'Feuilles ou légumes mijotés, tomate, oignon, huile, piment, épices. Viande, poisson ou accompagnement à confirmer.', 'À confirmer avec la partenaire.', 'confirmée', 'à valider', 'validée', true, false, 'draft'),
  ('saveurs-afrique-sauce-gombo', 'Saveurs d''Afrique', 'Sauce gombo', 'Sauce gombo onctueuse à la texture filante caractéristique, mijotée aux épices africaines. Servie avec l’accompagnement du jour selon disponibilité.', 'Plats', 13, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0159.jpg', true, 'Gombo, oignon, piment, épices, huile. Protéine et accompagnement à confirmer.', 'À confirmer avec la partenaire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-igname', 'Saveurs d''Afrique', 'Igname jus d''œuf', 'Igname pilée, lisse et élastique — cette pâte blanche traditionnelle est accompagnée d''une sauce tomate-oignon aux œufs durs, parfumée au piment et aux épices africaines. Un plat réconfortant où la douceur de l''igname rencontre l''acidité de la sauce tomate relevée.', 'Plats', 12, null, true, 'Igname pilée, œufs durs, tomate, oignon, piment, huile, épices.', 'Œufs.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('saveurs-afrique-monyo', 'Saveurs d''Afrique', 'Mônyo', 'Mônyo maison : sauce tomate-oignon relevée aux épices africaines, servie avec l’accompagnement disponible du jour. Plat parfumé, généreux et mijoté.', 'Plats', 12, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260612-WA0141.jpg', true, 'Tomate, oignon, piment, gingembre, ail, épices africaines, huile. Protéine et accompagnement à confirmer.', 'À confirmer avec la partenaire.', 'confirmée', 'à valider', 'validée', true, false, 'draft'),
  ('saveurs-afrique-spaghetti', 'Saveurs d''Afrique', 'Spaghetti', 'Spaghetti cuits al dente, enrobés d''une sauce tomate maison aux légumes frais (carottes, oignons, poivrons) et épices africaines — une version généreuse et parfumée des pâtes, simple et savoureuse.', 'Plats', 10, null, true, 'Pâtes (blé), tomate, carotte, oignon, poivron, épices, herbes.', 'Gluten.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('saveurs-afrique-salade', 'Saveurs d''Afrique', 'Salade béninoise', 'Salade composée fraîche et colorée façon buddha bowl : dés d''avocat fondant, thon émietté rose pâle, tomates juteuses éclatantes, œufs durs parsemés de poivre noir, oignons verts croquants et laitue fraîche. Chaque ingrédient est disposé séparément pour apprécier sa fraîcheur. Idéale pour un déjeuner léger et équilibré.', 'Plats', 10, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0157.jpg', true, 'Laitue, tomate, thon au naturel, œuf dur, avocat, oignon vert, poivre noir.', 'Poisson, œufs.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-bissap', 'Saveurs d''Afrique', 'Jus de bissap', 'Boisson rouge rubis intense à base de fleurs d''hibiscus (Hibiscus sabdariffa), infusée à froid et légèrement sucrée au sucre de canne. Servie bien fraîche sur glaçons avec une tranche d''ananas frais en garniture — la combinaison parfaite pour adoucir l''acidité naturelle du bissap. Naturellement désaltérante et riche en vitamine C.', 'Boissons', 5, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0160.jpg', true, 'Fleurs d''hibiscus, sucre de canne, eau, glaçons, ananas frais.', 'Aucun.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-yaourt', 'Saveurs d''Afrique', 'Yaourt simple 1L', 'Yaourt brassé maison, épais et onctueux, à la texture lisse et brillante. Fabriqué à partir de lait entier et de ferments lactiques. Vendu en pot d''un litre — idéal pour toute la famille, nature ou accompagné de fruits, miel ou confiture.', 'Desserts', 12, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0161.jpg', true, 'Lait entier, ferments lactiques.', 'Lait.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-degue', 'Saveurs d''Afrique', 'Dèguè 1L', 'Yaourt onctueux au couscous fin légèrement sucré — une spécialité maison à la texture unique entre le flan et le yaourt, avec le croquant subtil du couscous. Vendu en pot d''un litre.', 'Desserts', 15, null, true, 'Lait entier, couscous fin, sucre de canne, ferments lactiques.', 'Lait, gluten.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('saveurs-afrique-atchonmon', 'Saveurs d''Afrique', 'Atchonmon (Petits cailloux)', 'Atchonmon (Chin Chin) — petits dés de pâte sablée frits, dorés et croustillants, légèrement sucrés à la vanille. Une collation addictive à la texture ferme et friable, parfaite pour accompagner le thé, le café ou pour une pause gourmande à tout moment de la journée.', 'Snacking', 10, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0164.jpg', true, 'Farine de blé, œuf, sucre, beurre, vanille.', 'Gluten, œufs, lait.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('saveurs-afrique-dokor', 'Saveurs d''Afrique', 'Dokôr (beignets sucrés) 8u', 'Dokôr (puff-puff) — beignets moelleux et dorés, à la forme sphérique parfaitement ronde, légèrement croustillants à l''extérieur et d''une incroyable légèreté aérienne à l''intérieur. Des boules de pâte levée frites, idéales pour le petit-déjeuner ou la pause gourmande. Vendu par 8 unités.', 'Snacking', 5, 'https://delikreol.com/vendors/saveurs-afrique/drive-reimport/IMG-20260526-WA0163.jpg', true, 'Farine de blé, sucre, levure, vanille, œuf.', 'Gluten, œufs.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-abricot-pays', 'Gouté Mwen', 'Gouté Mwen — Abricot Pays', 'Glace artisanale à l''abricot pays. Douce et fruitée.', 'Desserts', 2, null, true, 'Abricot pays, sucre.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-super-coco', 'Gouté Mwen', 'Gouté Mwen — Au Nanan de Coco', 'Glace artisanale à la noix de coco. Sans sucre ajouté. Ingrédients : nan-nan coco et eau de coco.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-super-coco-ai.jpg', true, 'Nan-nan coco, eau de coco.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-api', 'Gouté Mwen', 'Gouté Mwen — API', 'Glace artisanale à l''ananas, piment végétarien. ‼️ Attention ça pique !', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-api-ai.jpg', true, 'Ananas, sucre, piment végétarien.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-mangue', 'Gouté Mwen', 'Gouté Mwen — Mangue', 'Glace artisanale à la mangue. Plein de saveurs des Antilles.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-mangue-ai.jpg', true, 'Mangue, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-canne', 'Gouté Mwen', 'Gouté Mwen — Canne (sans sucre ajouté)', 'Glace artisanale à la canne. Sans sucre ajouté. Naturellement sucrée par la canne fraîche.', 'Glaces', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-canne-ai.jpg', true, 'Canne.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-pasteque', 'Gouté Mwen', 'Gouté Mwen — Pastèque (sans sucre ajouté)', 'Glace artisanale à la pastèque. Sans sucre ajouté. Rafraîchissante.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-pasteque-ai.jpg', true, 'Pastèque.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-pomme-liane', 'Gouté Mwen', 'Gouté Mwen — Pomme Liane', 'Glace artisanale à la pomme liane, fruit exotique au goût unique.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-pomme-liane-ai.jpg', true, 'Pomme liane, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-citronnade', 'Gouté Mwen', 'Gouté Mwen — Citronnade', 'Citronnade artisanale faite avec le zeste du citron. Rafraîchissante et acidulée ! 🚨 Fait réellement avec le zeste.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-citronade-ai.jpg', true, 'Citron, zeste de citron, eau, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-ananas', 'Gouté Mwen', 'Gouté Mwen — Ananas (sans sucre ajouté)', 'Glace artisanale à l''ananas avec des morceaux d''ananas. Sans sucre ajouté.', 'Desserts', 2, null, true, 'Ananas, morceaux d''ananas.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-prune-cythere', 'Gouté Mwen', 'Gouté Mwen — Prune de Cythere', 'Glace artisanale à la prune de cythere (pomme cythere). Saveur tropicale authentique.', 'Desserts', 2, null, true, 'Prune de cythere, sucre.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-snow-boll', 'Gouté Mwen', 'Gouté Mwen — Snow Boll', 'Glace artisanale groseille et menthe. Très apprécié de tous, enfants compris. Rafraîchissant ! ❄️', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-snow-ball-ai.jpg', true, 'Groseille, sirop de menthe.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-kumquat', 'Gouté Mwen', 'Gouté Mwen — Kumquat', 'Glace artisanale au kumquat. Agrumes antillais au goût subtil.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-kumquat-ai.jpg', true, 'Kumquat, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-maracuja', 'Gouté Mwen', 'Gouté Mwen — Maracuja', 'Glace artisanale au maracuja (fruit de la passion). Exotique et fruité.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-maracuja-ai.jpg', true, 'Maracuja, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-prune-maracuja', 'Gouté Mwen', 'Gouté Mwen — Prune Maracuja', 'Glace artisanale prune de cythere et maracuja. Le mélange parfait !', 'Desserts', 2, null, true, 'Prune de cythere, maracuja, sucre.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-avocat-basi', 'Gouté Mwen', 'Gouté Mwen — Avocat-basi', 'Glace artisanale avocat et sirop de basilic. Original et surprenant !', 'Desserts', 2, null, true, 'Avocat, sirop de basilic.', 'À confirmer avec le prestataire.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-corossol', 'Gouté Mwen', 'Gouté Mwen — Corossol', 'Glace artisanale au corossol. Fruit crémeux aux vertues naturelles.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-corossol-ai.jpg', true, 'Corossol, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-mandarine', 'Gouté Mwen', 'Gouté Mwen — Mandarine', 'Glace artisanale à la mandarine. Agrumes frais et acidulés.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-mandarine-ai.jpg', true, 'Mandarine, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-cocktail', 'Gouté Mwen', 'Gouté Mwen — Cocktail', 'Glace artisanale cocktail — abricot pays, goyave et maracuja. Le mix parfait des Antilles !', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-cocktail-ai.jpg', true, 'Abricot pays, goyave, maracuja, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-clitoria-corossol', 'Gouté Mwen', 'Gouté Mwen — Clitoria / Corossol', 'Glace artisanale Gouté Mwen au clitoria et corossol, fraîche et florale, issue du kit import validé.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-clitoria-corossol-ai.jpg', true, 'Clitoria, corossol, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-pasteque-anis', 'Gouté Mwen', 'Gouté Mwen — Pastèque / Anis', 'Glace artisanale pastèque et anis étoilé. Un mélange rafraîchissant et original — la douceur de la pastèque rencontre les notes anisées. Nouveauté Tour des Yoles 2026 !', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-pasteque-anis-ai.jpg', true, 'Pastèque, anis étoilé, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-cerise-pomme-deau', 'Gouté Mwen', 'Gouté Mwen — Cerise / Pomme d’eau', 'Glace artisanale cerise et pomme d’eau, fraîche et locale. Visuel fourni par le partenaire, recette à confirmer avant activation commerciale.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-cerise-pomme-deau-ai.jpg', true, 'Cerise, pomme d’eau, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'à valider', true, false, 'draft'),
  ('goute-mwen-cerise', 'Gouté Mwen', 'Gouté Mwen — Cerise', 'Glace artisanale à la cerise, gourmande et rafraîchissante. Visuel fourni par le partenaire, recette à confirmer avant activation commerciale.', 'Desserts', 2, 'https://delikreol.com/vendors/goute-mwen/supplied-ai-20260722/goute-mwen-cerise-ai.jpg', true, 'Cerise, sucre.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'à valider', true, false, 'draft'),
  ('sweet-family-bao-poulet', 'Sweet Family Traiteur Orianne', 'Bao Bun Poulet', 'Bao bun vapeur moelleux, poulet mariné aux herbes antillaises. Min. 10 pièces.', 'Snacking', 1.8, 'https://delikreol.com/vendors/sweet-family/bao-buns.jpg', true, 'Pain bao vapeur, poulet mariné, herbes fraîches, pickles de légumes.', 'Gluten.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-bao-boeuf', 'Sweet Family Traiteur Orianne', 'Bao Bun Bœuf', 'Bao bun garni de bœuf mariné et poivrons caramélisés. Min. 10 pièces.', 'Snacking', 1.9, null, true, 'Pain bao vapeur, bœuf mariné, poivrons caramélisés, herbes fraîches.', 'Gluten.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('sweet-family-bao-boeuf-premium', 'Sweet Family Traiteur Orianne', 'Bao Bun Bœuf Premium', 'Bao signature : bœuf haché premium, garniture raffinée, sauce secrète. Min. 10 pièces.', 'Snacking', 2.5, null, true, 'Pain bao vapeur, bœuf haché premium, garniture raffinée, sauce secrète.', 'Gluten.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('sweet-family-landfood-solo', 'Sweet Family Traiteur Orianne', 'Land food solo', 'Côtes de porc grillées, pilons de poulet, saucisses, maïs, œufs — un plat généreux pour les amateurs de viande ! 🥩', 'Plats', 39.9, 'https://delikreol.com/vendors/sweet-family/landfood-solo.jpg', true, 'Côtes de porc, pilons de poulet, saucisses, maïs, œufs, épices.', 'Œuf.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-bao-bun-poulet', 'Sweet Family Traiteur Orianne', 'Bao Bun Poulet (boîte de 28)', 'Boîte de 28 bao buns garnis au poulet. Moelleux et savoureux, parfaits pour vos événements et cocktails ! 🥟', 'Apéritifs', 44, 'https://delikreol.com/vendors/sweet-family/bao-buns.jpg', true, 'Bao bun (farine, levure, eau), poulet effiloché, légumes croquants.', 'Gluten.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-nems-poulet', 'Sweet Family Traiteur Orianne', 'Nems poulet (pièce)', 'Nems poulet croustillants, dorés à souhait, servis sur lit de salade. Idéal pour l''apéritif ou le buffet ! 🥟', 'Apéritifs', 1.7, 'https://delikreol.com/vendors/sweet-family/nems-poulet.jpg', true, 'Galette de riz, poulet haché, légumes, épices.', 'Gluten.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-manchon-poulet', 'Sweet Family Traiteur Orianne', 'Manchon de poulet', 'Manchons de poulet dorés et assaisonnés, format apéritif ou buffet. Idéal pour compléter une commande événementielle.', 'Apéritifs', 1, 'https://delikreol.com/vendors/sweet-family/manchon-poulet.jpg', true, 'Manchons de poulet, marinade, herbes et épices.', 'Gluten.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-ti-nain-morue', 'Sweet Family Traiteur Orianne', 'Ti nain morue', 'Ti nain morue antillais — salade de morue émiettée, poivrons, oignons, persil, servie en coupelle sur lit de salade. Frais, savoureux, parfait pour l''apéritif ! 🥗', 'Apéritifs', 3.2, 'https://delikreol.com/vendors/sweet-family/ti-nain-morue.jpg', true, 'Morue émiettée, poivrons rouges et jaunes, oignons, persil, salade verte.', 'Poisson.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-chicken-wrap', 'Sweet Family Traiteur Orianne', 'Chicken Wrap', 'Wrap garni de poulet pané croustillant, laitue fraîche et fromage. Pratique et savoureux, idéal pour un snack rapide ou un buffet ! 🌯', 'Snacking', 2.5, 'https://delikreol.com/vendors/sweet-family/chicken-wrap.jpg', true, 'Tortilla, poulet pané, laitue, fromage.', 'Gluten, lait.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('sweet-family-pizza-vege', 'Sweet Family Traiteur Orianne', 'Pizza végé', 'Mini pizza végétarienne garnie de tomate, champignons, fromage et olive noire. Format pratique pour apéritif, buffet ou cocktail.', 'Apéritifs', 1.1, 'https://delikreol.com/vendors/sweet-family/pizza-vege.jpg', true, 'Pâte à pizza, tomate, champignons, fromage, olives noires, pousses fraîches.', 'Gluten, lait.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-colombo', 'Les Delices de Ninice', 'Le Colombo des Deux Rives', 'Colombo signature mêlant les épices des Caraïbes et du Suriname. Un plat généreux aux saveurs profondes.', 'Plats', 14, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0071.jpg', true, 'Viande, colombo, légumes, riz. Détails à confirmer avec le prestataire.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-moksi-vegetarien', 'Les Delices de Ninice', 'Le Moksi Aleisi Végétarien', 'Riz sauté surinamais aux légumes, version végétarienne. Simple, coloré et savoureux ! 🌿', 'Plats', 7, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0070.jpg', true, 'Riz, légumes variés, épices surinamaises.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-moksi-poulet', 'Les Delices de Ninice', 'Le Moksi Aleisi + Poulet', 'Riz sauté surinamais au poulet tendre. Recette traditionnelle maison, un délice ! 🍗', 'Plats', 10.5, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0072.jpg', true, 'Riz, poulet, légumes, épices surinamaises.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-moksi-porc', 'Les Delices de Ninice', 'Le Moksi Aleisi + Porc', 'Riz sauté surinamais accompagné de porc. Généreux et parfumé.', 'Plats', 11.5, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0073.jpg', true, 'Riz, porc, légumes, épices surinamaises.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-bami', 'Les Delices de Ninice', 'Bami des Îles', 'Nouilles sautées à la surinamaise, un classique revisité avec des influences caribéennes.', 'Pâtes', 14, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0074.jpg', true, 'Nouilles, viande, légumes, sauce soja, épices.', 'Gluten, soja. Autres allergènes à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-bara', 'Les Delices de Ninice', 'Bara + sauce signature', 'Beignet surinamais croustillant servi avec la sauce maison. Parfait en encas.', 'Snacking', 1.8, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0075.jpg', true, 'Farine, lentilles, épices, sauce signature.', 'Gluten (blé). Sans œufs ni produits laitiers.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-gulab-amande', 'Les Delices de Ninice', 'Gulab Jamun Amande', 'Douceur frite à base de lait, parfumée à l''amande et nappée de sirop.', 'Desserts', 0.8, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0076.jpg', true, 'Lait, farine, amande, sirop de sucre.', 'Lait, gluten, fruits à coque (amande). Autres à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-gulab-coco', 'Les Delices de Ninice', 'Gulab Jamun Coco', 'Douceur frite à base de lait, parfumée à la noix de coco et nappée de sirop.', 'Desserts', 0.8, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0077.jpg', true, 'Lait, farine, coco râpé, sirop de sucre.', 'Lait, gluten. Autres à confirmer.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-brochette-poulet', 'Les Delices de Ninice', 'Mini brochette Saoto Poulet', 'Mini brochettes de poulet marinées façon Saoto. Idéales pour l''apéritif.', 'Snacking', 2.5, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0078.jpg', true, 'Poulet, marinade Saoto, épices.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-brochette-porc', 'Les Delices de Ninice', 'Mini brochette Saoto Porc', 'Mini brochettes de porc marinées façon Saoto.', 'Snacking', 3, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0079.jpg', true, 'Porc, marinade Saoto, épices.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('ninice-brochette-boeuf', 'Les Delices de Ninice', 'Mini brochette Saoto Bœuf', 'Mini brochettes de bœuf marinées façon Saoto. La plus généreuse.', 'Snacking', 3.5, 'https://delikreol.com/vendors/ninice/drive-reimport/IMG-20260521-WA0080.jpg', true, 'Bœuf, marinade Saoto, épices.', 'À confirmer avec le prestataire.', 'confirmée', 'validée', 'validée', true, true, 'verified'),
  ('goute-mwen-cacahuete', 'Gouté Mwen', 'Gouté Mwen — Cacahuète (sans lactose)', 'Glace artisanale à la cacahuète, sans lactose. Onctueuse et gourmande, elle ravit les amateurs de saveurs authentiques ! 🥜', 'Desserts', 2, null, true, 'Cacahuète, lait végétal, sucre.', 'Arachide.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-pistache', 'Gouté Mwen', 'Gouté Mwen — Pistache (sans lactose)', 'Glace artisanale à la pistache, sans lactose. Onctueuse, parfumée et délicatement verte — un délice authentique des Antilles ! 🍦', 'Desserts', 2, null, true, 'Pistache, lait végétal, sucre.', 'Fruits à coque.', 'à confirmer', 'à valider', 'validée', false, false, 'draft'),
  ('goute-mwen-choco', 'Gouté Mwen', 'Gouté Mwen — Choco (sans lactose)', 'Glace artisanale au chocolat, cacao amer et eau de coco, sans lactose. Riche, onctueuse et intense — comme un voyage sous les tropiques ! 🍫🥥', 'Desserts', 2, null, true, 'Cacao, eau de coco, nan-nan (lait de coco), sucre.', 'Aucun.', 'à confirmer', 'à valider', 'validée', false, false, 'draft')
), resolved as (
  select i.*, v.id as vendor_id
  from imported i
  join public.vendors v on lower(regexp_replace(coalesce(v.business_name, v.name), '[^a-zA-Z0-9]+', '', 'g')) = lower(regexp_replace(i.vendor_name, '[^a-zA-Z0-9]+', '', 'g'))
)
insert into public.products(source_key, vendor_id, name, description, category, price, image_url, is_available, ingredients, allergens, photo_status, image_quality_status, description_quality_status, is_bankable, is_public, is_demo, status, updated_at)
select source_key, vendor_id, name, description, category, price, image_url, is_available, ingredients, allergens, photo_status, image_quality_status, description_quality_status, is_bankable, is_public, false, status, now()
from resolved
on conflict (source_key) do update set
  vendor_id = excluded.vendor_id,
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  image_url = excluded.image_url,
  is_available = excluded.is_available,
  ingredients = excluded.ingredients,
  allergens = excluded.allergens,
  photo_status = excluded.photo_status,
  image_quality_status = excluded.image_quality_status,
  description_quality_status = excluded.description_quality_status,
  is_bankable = excluded.is_bankable,
  is_public = excluded.is_public,
  is_demo = false,
  status = excluded.status,
  updated_at = now();

-- Approximate municipality/known-area centroids from the repository's partnerGeo map.
-- They support an explicitly approximate distance until a partner validates a precise address.
with geo(business_name, address, latitude, longitude) as (values
  ('Coco''s Food', 'Marché, 97211 Rivière-Pilote, Martinique', 14.4870, -60.9020),
  ('Snack Savè Peyi''A', 'Près du Pont de Fer, Rivière-Pilote, Martinique', 14.4870, -60.9020),
  ('Les Delices de Ninice', 'Barber Shop de Dillon, Fort-de-France', 14.6104, -61.0718),
  ('Sweet Family Traiteur Orianne', 'Les hauts de Dillon, 97200 Fort-de-France', 14.6104, -61.0718),
  ('Chef à Mada', 'Fort-de-France, Martinique', 14.6104, -61.0718),
  ('Saveurs d''Afrique', 'Cluny, Rivière-Salée, Martinique', 14.5100, -60.9650),
  ('An Tjè Coco', 'Fort-de-France, Martinique', 14.6104, -61.0718)
)
update public.vendors v set
  address = geo.address,
  latitude = geo.latitude,
  longitude = geo.longitude,
  location = extensions.st_point(geo.longitude, geo.latitude)::extensions.geography,
  delivery_radius_km = greatest(coalesce(v.delivery_radius_km, 3), 3),
  updated_at = now()
from geo where lower(coalesce(v.business_name, v.name)) = lower(geo.business_name);

update public.vendors
set logo_url = coalesce(logo_url,
  case
    when lower(coalesce(business_name,name)) = lower('Coco''s Food') then 'https://delikreol.com/vendors/coco/profile.svg'
    when lower(coalesce(business_name,name)) = lower('Chef à Mada') then 'https://delikreol.com/vendors/chef-a-mada/logo.jpg'
    else null
  end), updated_at = now()
where lower(coalesce(business_name,name)) in (lower('Coco''s Food'), lower('Chef à Mada'));
